"""Score a run against known ground truth.

Every accuracy claim in this repository has so far been "unmeasured", because
there was no labelled set. For the two synthetic fixtures there is one: they are
generated by make_fixture.py from literal strings, so the exact set of numbers on
each page is known. That is enough to measure the things that actually matter for
a clinical document:

  missed     a number that is on the page and did not come out. Silent data loss.
  spurious   a number that came out and is not on the page. Silent fabrication.
  review     how many numbers were flagged for a human. The cost of safety.

These fixtures are clean, synthetic and Latin/Greek. They are the easiest input
any of these modes will ever see, so treat the numbers as an upper bound and a
way to compare modes against each other -- not as a prediction of field accuracy.

    .venv/bin/python evaluate.py output/granite_ocr/audit.json
    .venv/bin/python evaluate.py output/*/audit.json --table
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
from collections import Counter
from decimal import Decimal, InvalidOperation

import numeric

# Page 1 of test_record.pdf == euro_table_sample.png
EURO = ["1.284,50", "2 019,75", "3 304,25",
        "987,31", "1.556,40", "2 543,71",
        "3.412,66", "1 073,82", "4 486,48",
        "845,09", "2.764,53", "3 609,62",
        "18,7", "42,3",           # Wzrost 18,7% -- Ανάπτυξη 42,3%
        "1", "2"]                 # Kwartał 1, Kwartał 2

# Page 2 of test_record.pdf == table_sample.png
ENG = ["1,284.50", "2,019.75", "3,145.08", "6,449.33",
       "987.31", "1,556.40", "2,208.19", "4,751.90",
       "3,412.66", "1,073.82", "5,690.14", "10,176.62",
       "845.09", "2,764.53", "1,938.77", "5,548.39",
       "6,529.56", "7,414.50", "12,982.18", "26,926.24",
       "18.7", "42.3"]           # Growth: 18.7% YoY, margin 42.3%
# NOT listed: the 1/2/3 in the "Q1 Q2 Q3" headers. numeric.extract deliberately
# refuses a digit glued to a letter -- that guard is what stops "B12 450"
# becoming 12450 -- so extract("Q1") == [] by design. Asking for them made three
# permanently unreachable misses look like a pipeline failure. The euro page's
# "Kwartał 1" headers ARE listed, because the space makes them reachable.

TRUTH = {"test_record.pdf": [EURO, ENG],
         "euro_table_sample.png": [EURO],
         "table_sample.png": [ENG]}


def canon(raw: str):
    """A value's canonical decimal, so 1.284,50 and 1,284.50 compare equal."""
    v, _ = numeric.normalise(raw)
    if v is None:
        return None
    try:
        d = Decimal(v)
    except InvalidOperation:
        return None
    return str(d.quantize(Decimal(1)) if d == d.to_integral_value() else d.normalize())


def value_of(rec):
    """The canonical value a resolution reports, from its key."""
    key = rec.get("value") or ""
    parts = key.split(":")
    body = parts[1] if len(parts) >= 2 else key
    # ranges/ratios carry two values; count both
    return [c for c in (canon(p) for p in body.split("/")) if c is not None]


def score(audit_path: str):
    d = json.load(open(audit_path, encoding="utf-8"))
    src = (d.get("input") or "").split("/")[-1]
    truth_pages = TRUTH.get(src)
    if truth_pages is None:
        return None

    per_page, tot = [], Counter()
    for i, page in enumerate(d.get("pages", [])):
        if i >= len(truth_pages):
            break
        expected = Counter(c for c in (canon(t) for t in truth_pages[i]) if c)
        found = Counter()
        review = 0
        for rec in page.get("numbers", []):
            for v in value_of(rec):
                found[v] += 1
            if rec.get("needs_review"):
                review += 1
        hit = expected & found            # multiset intersection
        per_page.append({
            "page": i + 1,
            "expected": sum(expected.values()),
            "found": sum(found.values()),
            "correct": sum(hit.values()),
            "missed": sorted((expected - found).elements()),
            "spurious": sorted((found - expected).elements()),
            "review": review,
        })
        tot["expected"] += sum(expected.values())
        tot["found"] += sum(found.values())
        tot["correct"] += sum(hit.values())
        tot["missed"] += sum((expected - found).values())
        tot["spurious"] += sum((found - expected).values())
        tot["review"] += review

    toks = sum(p.get("vl_prompt_tokens", 0) + p.get("vl_completion_tokens", 0)
               for p in d.get("pages", []))
    return {
        "mode": d.get("mode", "?"),
        "model": (d.get("vl_model") or "").split("/")[-1],
        "verify": d.get("verification"),
        "line_reads": d.get("vl_line_reads"),
        "pages": per_page,
        "totals": dict(tot),
        "recall": tot["correct"] / tot["expected"] if tot["expected"] else 0.0,
        "precision": tot["correct"] / tot["found"] if tot["found"] else 0.0,
        "tokens": toks,
        "vl_calls": sum(p.get("vl_calls", 0) for p in d.get("pages", [])),
        "wall": d.get("wall_seconds"),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("audits", nargs="+")
    ap.add_argument("--table", action="store_true")
    args = ap.parse_args()

    paths = []
    for a in args.audits:
        paths.extend(sorted(glob.glob(a)) if "*" in a else [a])

    rows = []
    for p in paths:
        try:
            r = score(p)
        except Exception as exc:
            print(f"  {p}: could not score ({exc})")
            continue
        if r is None:
            print(f"  {p}: no ground truth for this input")
            continue
        r["path"] = p
        rows.append(r)

    if not rows:
        sys.exit("nothing scored")

    if args.table:
        print(f"{'mode':15} {'reads':6} {'recall':>7} {'prec':>7} {'miss':>5} "
              f"{'spur':>5} {'review':>6} {'calls':>6} {'tokens':>7} {'wall':>7}")
        print("-" * 88)
        for r in sorted(rows, key=lambda x: (x["mode"], str(x["line_reads"]))):
            t = r["totals"]
            print(f"{r['mode']:15} {str(r['line_reads']):6} "
                  f"{r['recall']*100:6.1f}% {r['precision']*100:6.1f}% "
                  f"{t['missed']:5} {t['spurious']:5} {t['review']:6} "
                  f"{r['vl_calls']:6} {r['tokens']:7} {r['wall'] or 0:6.1f}s")
    else:
        for r in rows:
            t = r["totals"]
            print(f"\n{r['mode']}  ({r['model']}, line_reads={r['line_reads']})")
            print(f"  recall {r['recall']*100:.1f}%  precision {r['precision']*100:.1f}%")
            print(f"  expected {t['expected']}, found {t['found']}, correct {t['correct']}, "
                  f"missed {t['missed']}, spurious {t['spurious']}, flagged {t['review']}")
            for p in r["pages"]:
                if p["missed"] or p["spurious"]:
                    print(f"    page {p['page']}: missed {p['missed']} | spurious {p['spurious']}")


if __name__ == "__main__":
    main()
